### ISSUE TITLE
contract attribute causes ICE in earlier function

### ISSUE THREAD

**Issue by rollbear** [arcosuc3m/clang-contracts#16]
Apologies for not having been able to reduce this more.

In the code, linked to compiler explorer below, one specific contract attribute breaks the compiler. Comment it out, and everything is fine. I don't really see the connection between them.

Comment out the post condition on line 128 (marked "the culprit") for successful compilation.

[compiler explorer](http://fragata.arcos.inf.uc3m.es/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5NwDMeAGYssCgNQAlAPIAZbT2wBBdQH0AygBUD5gJIBhYwDVst85pMAJAAqeOABgNyKngsmBo6eoYmFlZ2js6uHt5%2BAf5ywcgMIliqHLK2IgR4DIQAnrnYyWksGVmhubaCBFgAHhIADgTllVzy1ZnZ9QC2mIMkZbIVqT3p/XV5yI3EwcBdqf4sTMOCbUwSqsSoDAwARphMxDkA7HxrKQYEI23MDzl5BCVtmBvDquakqo10CAQII8AAvTDGAiqAByqwMGSYgkEAIITEKyGMADdMMgiMRKtdkm0RMdisgQMlVKoRKC2ADwZD3p9XgARVFAkGMqG5G4GNpLLHoyRU1RY1B4dAAKlUTHQ6GIEFBEKhH1CkuaAEpVCxUJhWpgOlcePtMAQxCxVMcRAoFJgLvxVBqpcrMKgFBBzJreRxLqzReYZR1Fa7VSyNdrdfr2tDfSbiGaLaj0XhMcgkZ08oHyhA5QqIBHvbI%2BH7RWgWI1fkGCCHucz1egtapy5WowajXHTebiJbGim0xn6i3odmJrn5YrCz7S/5qcOxRLpbKJ0q62qnY3tfO2zHjV2k9bbfacrwN80XYz3Z6iyX/bOGSr66pMAwRl8CCjcuzfD770xisAGyCNezYIOcVo2naBIAKw8DCF4QleXocNB/rFsSpLkpS96IsiToPMQ6IkKKcaitSgaqLGsjsiwIhHMGv53NS1IKEsXzoM2zB4X2GLYri%2BKMdSJJkqm2EGMxNJ0sA%2BH2kRxDGOmDzAGMbIcsChHKKggzGLsEjIsYhCyfiUJMCs6H3tStLLGK/4iEy65fr8gnMVZ9L4EeCbVPZLKOQwqBsM5llSaaUFfHsjnmNwABsgWSdZbQSiwBGqaOfJkTJhH4hA2qOSoTB0ZmaUWSF9phaEqCfJlJBStlzb%2BY06UoXwsH6p8eKCCAlGqGAYCObR9E1ih/qoY11z7j2qhSoVvp3uJzEJcEyUVUZJAALQ5lu9WdMVTVNa1/EdV1PV9XRDAMSNI07WNCbdpa00znN1KGVVBJcFFqjLS9/D8LVnbfbwhXjZaU0IHggjTrNEnPXJH2VXJ/08AWSU5WN%2BVEPsWKqSDYO8iefAA7jN1JsQWIQ1S6XHKghywytBLUV%2BBYETDeCbRWsbXYmE1UWh7J4AAdPdaF8hJlPU59cnHdRjO006rOVp2RMTT1EDY5%2B9PUbLZOzqKAp4EKDxiVDTNZRRBDGNqnWdNcZszcaM0kaW5lMXVbOtRcoZPumOzIKUtXbnq7bs/GnOWnC6EPXOW1uw%2B3mhK6ftbTqAe7grIfPq%2BwxJeD4eQy7jTR6LDDPoMHQlAnbNJ9GhpB0DMe/er34AKpa87PGpnxeIkPX7J5QVjGim3mI4p3irzoPHcCW9%2ByRsn1dKk0wJg8YuoEAgBwAO4KRVJRb2zxAiHieBkpCpNZuU3q3NSpHFYoecPM0AqqPPnJLzWet4P%2BDA72gbTf1t%2B%2BH2PtieokUJgX0enbYq1JATAmGIMZAv8ICHigv8YgfNkH2lQXzF8b4s4ITdB6L0N5Rq52pC%2BQQ6o1DDmjs/Reghl6oFXhvLev9d6LAPoUIBp8XDn1GsLCSqgFAkCfh7J0qkfzFjEZLdkaCcGZw/LjBGLN0pXyJFA5iIR17jnzCzbU5gVZoODAWTUxD1H2yuqQ9OFC%2BEqLUlyR8YjHISP4RJGsJRIEQIkuvUGr4n54FeLYfY2CM7vkEOAgRzFr6eIEZop%2BeZJwmN%2BAYvmRi8CrVWiY2KElzHRJyRExSyAEBPz5iU8JAiokROpN4oooQCyvGwKoXwZSIkVMqdAheIAsCLFQDvdEEAjHpN0VkyJEdKlMNQOvYZeSRmWLkaE1SsiQlZ2cjk0UDwS7PDmLYes3xQgOBSv8GBIAvhMCAYoHkeQjlLxXmvCZxhRg4jYTWDhR9XzALyA4LoEwZQnQGnTSYc1x7DyykC/ixE3rRWnpXQODsXFOioVHB%2BFxaEgFfoKD%2BRwd4PMhMOABnC3ncNAdgZpHiIlHLgQgsuGCyBBOpVguZeDXRIUyU7bJoyyEMGsVdOFLFhGrgcf4pxuN/HSKCQyhRkilEktUTyjRmAtHxOMXolF2LkmpJMaY3J7KrizKWR%2BBZwTcESv4as%2B8AA/UFI9ao7jnlc%2BhNzmFdOeYAglIDeH3laby5FaNUCQqYKoTqqsUYmiOU6g4vSCAQGikwYhozpnQ3xFaTAwBgi/Q5rdY0Rimn2xzqKBNwj2JpuDhmuMRjxVhJzbeSo95IpT2OLsAA1ta2eHQSKwT2g/A6nUeqPHeNlIaA6PVqIgYrS0KtV5g29C1PVghVq0AHaynVazHibICTszYoQSl81%2BNnAF5FIUrt2JCetyAm3mHBhCqeW7KJhOhTGFF1zGG3M3ril5XCQH/HPVu91c1dotU7e1Tq8ccp5GbEwb2vsp3DVzn%2BngXxBBiEwCiYgnVooOgbieKKJ6m1QaGqoAA9PhgJ6TKIIFCMgOiusCDHSHXC0dk1YnaMVOWhGiT9FHKEcQde5x0AgN3RAD8mot2atUbNXW%2BsRSpEdkVO4pqAg9HYrfQj1ItC6H0EYMwlgbD2CcC4NwxgvCeCkJqRg0hoJSFICwaQvgLOoGkLYBGAJRDiDqD0WgFmCDWeMyZhtIBZCyD5v5oLwWQtRVM1IAALBZqzUgbOkDs1ICzHVfCkE87F4zpA4CwCQGgEuNSyAUAgLlto%2BWUDMACrwfgq1BgZkwQoIoBEOpIK86QY4wRzglGkO50guX5GaBYF/FrWAatsFfENvACZD44g6ul0g%2BpcQFEkFIbri0XwtbfoMLzJnyvsARowI%2BHVIAmYqoUeq0hVqAi/JwSrvAuBMCS85iQdBttmeiy1hLtgduqCinzXwv3VDNAABxRWMFFCLORYKIjYKtcsNZdgKNQk/Gr%2BdiDaggLgQgwi5D0FULYLSJXXwOjc9qBzN2eAea2z5vzAWQu06C2Fhg0gouWfe9IJLIAUtpZsyZrLiAQCiAICSAg5BKDFdK/QTA%2BB8TPfC%2BZlns2EvY9UOvQgRTPusGkj9v7vgAfA9B%2BDpqUPgAw/8nD9qeGIDI4IpqCn6WTGkF8/5wLdPafheZzFuLCX2ec8p%2BFrgb2Fds9S77nExBQT%2BRABFoAA)

**Comment by jalopezg-uc3m** [comment]
Closed in commit 7257763.
CAUSE: Broken declaration chain.  The identifier (r) that refers to the return value in [[ensures r: ...]] has FETokenInfo replaced permanently.
SOLUTION: Save FETokenInfo and restore it after parsing expression.
