### ISSUE TITLE
Compiler explorer link broken

### ISSUE THREAD

**Issue by akrzemi1** [arcosuc3m/clang-contracts#22]
Hello,
The README page contains the link to CompilerExplorer. the link is not working. any chance of fixing it?

**Comment by jalopezg-git** [comment]
Hi @akrzemi1,

I am sorry to inform that we discontinued the maintenance of the machine that was hosting the service.  What I can suggest is that you setup your own CompilerExplorer instance, and that you add your own build of `clang-contracts` as a compiler.  To that end you will have to:

1. Build `clang-contracts` following the instructions [here](https://github.com/arcosuc3m/clang-contracts/blob/master/README.md#build-instructions-of-llvm--clang).  These instructions assume that you have `git` and a working C++ toolchain installed.
If you are not going to hack on `clang-contracts`, I would suggest adding `-DCMAKE_BUILD_TYPE=Release` command line option to CMake.
Note that building LLVM+clang might take some time, depending on your hardware.

2. Follow the instructions [here](https://github.com/compiler-explorer/compiler-explorer#developing) to setup your own instance of CompilerExplorer.  Also, you might need to install some dependencies, e.g. Node.js.

3. Add `clang-contracts` as a compiler to CompilerExplorer following [this guide](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingACompiler.md).  Note that you will have to specify the absolute path to the `clang++` binary generated in step 1.

Cheers,
Javier.
